spring:
  output:
    ansi:
      enabled: always
  application:
    name: SpringModulithKickstart
  profiles:
    active: ${ACTIVE_PROFILE:dev}
management:
  endpoints:
    web:
      base-path: /admin/actuator
      exposure:
        include: health, info, modulith