spring:
  output:
    ansi:
      enabled: always
  application:
    name: SpringModulithKickstart
  profiles:
    active: ${ACTIVE_PROFILE:dev}
security:
  jwt:
    secret-key: =3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000 # 1 hour expiration
admin:
  email: ${ADMIN_MAIL:admin@admin.com}
  password: ${ADMIN_PASSWORD:admin}
  full-name: Admin
springdoc:
  swagger-ui:
    path: /admin/swagger
  api-docs:
    path: /admin/api-docs
management:
  endpoints:
    web:
      base-path: /admin/actuator
      exposure:
        include: health, info, modulith